### ISSUE TITLE
EULA window not opened.

### ISSUE THREAD

**Issue by saronpasu** [TatriX/rogalia#112]
EULA window not opened.
This bugs happened only Steam's version GameClient.
github's version GameClient (NW.js) not happened.

see screenshot.

![ScreenShot](https://raw.githubusercontent.com/saronpasu/misc/master/img/rogalia_eula_bugs.png)

**Comment by msstnk** [comment]
I just sent a pull request for this, added 3 files, eula.ja.txt, eula.ru.txt, eula.en.txt.
Russian is not my mother tongue tho I could not translate it into Russian.
Can you translate Russian one for us?

**Comment by TatriX** [comment]
No one read those in Russia ;) Thank you, I'll merge PR asap.

2017-02-18 6:20 GMT+03:00 msstnk <notifications@github.com>:
