### ISSUE TITLE
fishing tool + "R" command. dont open detail fishing window.

### ISSUE THREAD

**Issue by nakawankuma** [TatriX/rogalia#116]
I fishing equipment.
mouse click and "space" fishing is NP.
but "R" command is dont open window never.

**Comment by TatriX** [comment]
Sorry, could you please give a step-by-step guide on how can I reproduce the issue?
I can repeat finishing by pressing R.

**Comment by AGPDev** [comment]
i dont have this problem, i think about time if dont have comunication you can close this.
