### ISSUE TITLE
Suggestion: Option to remove fence

### ISSUE THREAD

**Issue by AGPDev** [TatriX/rogalia#157]
I cant select fence to destroy or move.

![cerca](https://cloud.githubusercontent.com/assets/5721341/26563792/20791d2c-44ae-11e7-8f3d-f04f458bea74.png)

**Comment by TatriX** [comment]
There are several ways to do it.
1) Use `ctrl` to select (works when you outside the fence)
2) Use `ctrl+x` (detector key in the GUI)

**Comment by AGPDev** [comment]
Work, thank you.
