### ISSUE TITLE
Идеи по дизайну персонажей

### ISSUE THREAD

**Issue by Vampireos** [TatriX/rogalia#159]
Хотелось бы самую малость увеличить, дабы было видно мелкие детали.
![2017-06-05 02 08 31](https://cloud.githubusercontent.com/assets/1193738/26766355/e1738f8c-4998-11e7-856e-3f3b7e90f90e.png)
![2017-06-05 01 35 02](https://cloud.githubusercontent.com/assets/1193738/26766356/e17624ae-4998-11e7-91ac-673cdf0c3a42.png)

**Comment by TatriX** [comment]
Тогда нужно будет все пропорционально увеличивать. У нас нет таких ресурсов.
