### ISSUE TITLE
Выпадающие квесты

### ISSUE THREAD

**Issue by SaintBenedict** [TatriX/rogalia#2]
Запилить выпадающий список не в ебенях, а по середине экрана.

**Comment by TatriX** [comment]
Надо вообще убрать выпадающий список и сделать все переходы между диалогами внутри одного окна.
Вопрос сохранять ли размеры окна при переходах или под размер контента уменьшать/увеличивать?

**Comment by SaintBenedict** [comment]
Да, правильная мысль. Размеры окна сохранять. Изменение будет очень бить по глазам.
