### ISSUE TITLE
PT-BR Translation

### ISSUE THREAD

**Issue by GabrielCoelho** [TatriX/rogalia#206]
## Hello everyone. 

I'm here to know if there's **any intention** to translate the game for any other language; as I'm Brazilian, I could translate it to PT-BR. 

Best Regards,
_**Gabriel Coelho Soares**_

**Comment by GabrielCoelho** [comment]
Sorry, I didn't enter the game before started this issue. It's already translated

**Comment by TatriX** [comment]
Feel free to update the translation.
