### ISSUE TITLE
Коллизия столба

### ISSUE THREAD

**Issue by kolyann** [TatriX/rogalia#43]
Столб (Деревянный забор: Столб) требует для строительства 2 бревна, визуально занимает две клетки, однако имеет коллизию всего на одну.
![2015-10-16 20-22-22](https://cloud.githubusercontent.com/assets/12108865/10548479/be6a2b3a-7443-11e5-81e9-274d75eb52e3.png)

**Comment by TatriX** [comment]
Это сделано специально, чтобы визуально при стыковке с остальными секциями смотрелось нормально.
