### ISSUE TITLE
Проникновение на чужой клейм

### ISSUE THREAD

**Issue by Raycheek** [TatriX/rogalia#57]
Сообщили игроки: 
Serfess
Суть проблемы:
Можно проникнуть на чужой огороженный клейм. Поэтапно:
1. С нейтральной территории поставить у ворот заготовку под табурет.
2. Поставить рядом еще одну заготовку
3. Сделать два табурета, на один сесть, другой взять в руки.
4. Поставить табурет за ворота внутрь клейма и пересесть на него.

**Comment by TatriX** [comment]
Исправлено в v0.21
