### ISSUE TITLE
Кролики

### ISSUE THREAD

**Issue by nukerrogal** [TatriX/rogalia#68]
Пытаюсь разводить кроликов: 

http://prnt.sc/cj0izj

http://prnt.sc/cj0iom

По 2 кролика в отдельных клетках покрываемых деревянными корытами с кормом. Корм - трава.
Жрут траву, весьма успешно. Живут уже пару суток.
Не размножаются.

**Comment by TatriX** [comment]
Разнополые?

**Comment by nukerrogal** [comment]
ну да, везде ведь написано, шо они бывают разнополые. Спасибо, вопрос закрыт.

**Comment by TatriX** [comment]
Шифт зажимаешь и виден пол/уровень моба.

**Comment by nukerrogal** [comment]
**падёж скота**
http://prnt.sc/cj47sc
в центре корыто с травой
одна корова прост перестала жрать.
полоска жизни ползёт вниз... и она падает мертвая.
такое чувство, что чтобы скот жил - его нужно ставить в тесные боксы  - в которых они никуда не смогут ходить и перед мордой кормушка.

**Comment by nukerrogal** [comment]
сутки прошли и ещё одна корова покинула бренный мир
http://prnt.sc/cjhwyp
http://prnt.sc/cjhx5n
