### ISSUE TITLE
Масштаб десктоп клиента

### ISSUE THREAD

**Issue by SergiiVlasiuk** [TatriX/rogalia#78]
Запустил игрушку по клиенту
http://rogalia.ru/downloads/rogalia-linux64.zip

Но диагональ моего ноута 15 дюймов и картинка слишком большая для моего экрана.
Пробовал отрегулировать клиенту zoom, Но безуспешно. в настройках касательно этой темы тоже ничего не обнаружил.

**Comment by TatriX** [comment]
Разрешение экрана какое?

**Comment by SergiiVlasiuk** [comment]
1366х768

**Comment by TatriX** [comment]
Игровая область 1280x720. В полноэкранном режиме должно быть нормально. Может я не понимаю сути; скриншот думаю поможет.

**Comment by SergiiVlasiuk** [comment]
Не знаю как сюда скрин загрузить.
Игровая область - действительно на весь экран.
Когда играл в браузере - изменяя масштаб я мог уменьшить ее, и оставалось место за пределами карты для размещения открытых сумок. Сейчас открытые сумки перекрывают карту действий.
Сами сумки уменьшить не могу, нет у них промежуточных состояний (миниммизированных), чтоб ослабить эффект перекрытия. Не обладают они так же эффектом просвечивания.

**Comment by TatriX** [comment]
ctrl+wheel для зума.
