### ISSUE TITLE
Топ прочность

### ISSUE THREAD

**Issue by SergiiVlasiuk** [TatriX/rogalia#83]
@TatriX 

Видел ашот ночью хвастался в чат титановым ножем (ку100 и прочность около 5 000).
В общем какой рецепт и материалы должен использовать грантмастер, чтоб иметь такое чудо!?
Аналогичноо интересует молот и щит (макс ку и прочность в тысячах).
Jadesoturi.

**Comment by ramashka** [comment]
Материалы те-же самые, рецепт - следующий(воспользоваться им ты не сможешь, но посмотреть - запросто), набери в консоли хрома:
`game.player.IsAdmin=true`
Далее ПКМ по ножу -> $cmd -> $prompt -> "set-durability 5000". В чате появится соответсвующая запись, и если ты TRUE grandmaster/IsAdmin, то по нажатии Enter - получишь нож с прочностью в 5000.

**Comment by SergiiVlasiuk** [comment]
Ашот TRUE grandmaster/IsAdmin? Или это бага после обновлений по факту изменения формул качества\прочности!?

**Comment by TatriX** [comment]
1) Наиболее вероятно что это старый предмет, когда показатели прочности были как раз такого порядка. В ближайшем апдейте это все будет исправлено.
2) Предмет который линканули в чат это просто текст. Туда можно написать что угодно.
3) У Ашота не админских прав.

**Comment by SergiiVlasiuk** [comment]
Спасибо.
Если прочность старых предметов будет пересмотрена и исправлена, то воспрос исчерпан.
