### ISSUE TITLE
Квест Платона в городе.

### ISSUE THREAD

**Issue by spaut33** [TatriX/rogalia#85]
После окончания обучения я попадаю в город, встречаюсь с Платоном, сдаю квест без награды и появляется кнопка "Принять", которая выдает внутреннюю ошибку сервера.
![image](https://cloud.githubusercontent.com/assets/5065694/21072194/261be6a6-becb-11e6-8589-edbeb12a9598.png)

**Comment by TatriX** [comment]
Механику квестов обновили, этой ошибки быть больше не должно.
