### ISSUE TITLE
Broken assets on windows

### ISSUE THREAD

**Issue by fabianPas** [TatriX/rogalia#94]
In the latest master the smelter and oven are invisible. Is this a client bug or a server/client version incompaibility issue?

**Comment by TatriX** [comment]
Master? You are using local installation?

**Comment by fabianPas** [comment]
Latest master branch. Yes I am using a local installation.

**Comment by TatriX** [comment]
Could you give me more info about your installation. How you run it, what OS do you have?

**Comment by fabianPas** [comment]
Sure! My steps:

Windows x64
Forked the latest master branch
Ran NPM install with Node version 6.9.1
Downloaded nw.js 19.4 x32 SDK as the greenworks library used for Windows is x32 and otherwise you will get an error about greenworks lib missing.
I created a steam_appid.txt with the Rogalia app ID 528460.
Then I dragged the rogalia directory onto nwjs.exe
And I can run it.

**Comment by TatriX** [comment]
I think you problem is 
> Windows x64
There are a lot of symlinks in the assets directory, which is broken on windows. You should run `npm run steam` to build a zipped client which should work on windows.

What about missing libraries? Probably I've missed something.

**Comment by fabianPas** [comment]
Even after `npm run steam` or `gulp nwbuild` it's still not showing the smelter etc.

About missing libraries I received an error about the greenworks library not being found when running Rogalia using an x64 nwjs executable. 

Also, is there a way to chat with you? Are you available on a discord channel etc? It would be nice for contributors to discuss in-game functionality with you. For example when developing quality of life changes.

**Comment by TatriX** [comment]
https://discordapp.com/channels/266625965193428994
run `dist/build/rogalia/win32/rogalia.exe`

**Comment by fabianPas** [comment]
The discord URL is invalid unfortunately.

I have run that binary already. Although it now gives me an unable to initialize Steam error.

**Comment by TatriX** [comment]
Yes, you should run the steam app in the background.
https://discord.gg/kvyp3R2

**Comment by TatriX** [comment]
So the problem is broken symlinks. We need to find a way to fix this on windows.
